# Generated by Django 5.0.1 on 2024-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_app', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_of_team',
            field=models.CharField(default='Default team name', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
