# Generated by Django 5.0.1 on 2024-02-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jersey_app', '0005_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='clubs',
            field=models.ManyToManyField(to='jersey_app.club'),
        ),
    ]
